server:
  port: 3000

dir:
  static: public
  controller: lib/www/controller
  presenter:
    view:
      include: include
      template: template

uri:
  static: /static

redis:
  -
    hostname: localhost
    port: 6379
  -
    hostname: localhost
    port: 6380

